E-Belediye.UI/Models/ErrorViewModel.cs
namespace E_Belediye.UI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

E-Belediye.UI/Controllers/AnalysisController.cs
using Microsoft.AspNetCore.Mvc;

namespace E_Belediye.UI.Controllers
{
    public class AnalysisController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

E-Belediye.UI/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;

namespace E_Belediye.UI.Controllers
{
    public class EmployeeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AddEmployee()
        {
            return View();
        }

        public IActionResult EmployeeList()
        {
            return View();
        }
    }
}

E-Belediye.UI/Controllers/HomeController.cs
using E_Belediye.UI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace E_Belediye.UI.Controllers
{
    public class HomeController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

E-Belediye.UI/Controllers/MessageBoxController.cs
using Microsoft.AspNetCore.Mvc;

namespace E_Belediye.UI.Controllers
{
    public class MessageBoxController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

E-Belediye.UI/Controllers/PastTransactionsController.cs
using Microsoft.AspNetCore.Mvc;

namespace E_Belediye.UI.Controllers
{
    public class PastTransactionsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

E-Belediye.UI/Controllers/TaskProcessController.cs
using Microsoft.AspNetCore.Mvc;

namespace E_Belediye.UI.Controllers
{
    public class TaskProcessController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

E-Belediye.UI/Views/Analysis/Index.cshtml
@{
    ViewData["Title"] = "Analizler";
    Layout = "_Layout";
}

<head>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link rel="stylesheet" href="~/css/analysis/analysis.css" asp-append-version="true" />
</head>
<body>
    <h1>Analizler</h1>

    <div class="personelChartAnalysis">
        <canvas id="personelChart"></canvas>
        <script src="personel-analysis.js"></script>
    </div>

    <div class="processAnalysis">
        <canvas id="operationsChart"></canvas>
        <script src="process-analysis.js"></script>
    </div>
    
    <script src="~/js/analysis/employeeAnalysis.js"></script>
    <script src="~/js/analysis/processAnalysis.js"></script>
</body>

E-Belediye.UI/Views/Employee/AddEmployee.cshtml
@{
    ViewData["Title"] = "Personel Ekle";
    Layout = "_Layout";
}

<head>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link rel="stylesheet" href="~/css/employee/employee.css" asp-append-version="true" />
</head>

<h1>Personel Ekle</h1>
<section class="add-person-container">
    <header>Personel Kayıt Formu</header>
    <form action="#" class="form">
        <div class="input-box">
            <label>İsim Soyisim</label>
            <input type="text" placeholder="İsim Soyisim Giriniz" required />
        </div>
        <div class="input-box">
            <label>E-Posta Adresi</label>
            <input type="text" placeholder="E-Posta Adresinizi Giriniz" required />
        </div>
        <div class="column">
            <div class="input-box">
                <label>Telefon Numarası</label>
                <input type="number" placeholder="Telefon Numaranızı Giriniz" required />
            </div>
            <div class="input-box">
                <label>Doğum Günü</label>
                <input type="date" placeholder="Enter birth date" required />
            </div>
        </div>
        <div class="gender-box">
            <h3>Cinsiyet</h3>
            <div class="gender-option">
                <div class="gender">
                    <input type="radio" id="check-male" name="gender" checked />
                    <label for="check-male">Erkek</label>
                </div>
                <div class="gender">
                    <input type="radio" id="check-female" name="gender" />
                    <label for="check-female">Kadın</label>
                </div>
            </div>
        </div>
        <div class="input-box address">
            <label>İkametgah Adresi</label>
            <input type="text" placeholder="Mahalle Bilgisini Giriniz" required />
            <input type="text" placeholder="Sokak ve diğer bilgileri giriniz" required />
            <div class="column">
                <div class="select-box">
                    <select>
                        <option hidden>Ülke</option>
                        <option>Türkiye</option>
                        <option>Avrupa Vatandaşı</option>
                        <option>Amerikan Kıtası Vatandaşı</option>
                        <option>Orta Doğu Vatandaşı</option>
                        <option>Asya Vatandaşı</option>
                    </select>
                </div>
                <input type="text" placeholder="İl" required />
            </div>
            <div class="column">
                <input type="text" placeholder="İlçe" required />
                <input type="number" placeholder="Posta Kodu" required />
            </div>

        </div>
        <div class="input-box">
            <label>Çalışma Bilgileri</label>
            <div class="column">
                <div class="select-box">
                    <select>
                        <option hidden>Çalışacağı Birim</option>
                        <option>Bilgi İşlem</option>
                        <option>Hizmet Birimi</option>
                        <option>Destek Birimi</option>
                    </select>
                </div>
                <input type="text" placeholder="Ünvan" required />
            </div>
        </div>
        <button type="submit">Ekle</button>
    </form>
</section>


<div class="recent-orders">
    <h2>Eklenen Son 5 Personel</h2>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Ad Soyad</th>
                <th>Birimi</th>
                <th>İşe Başlama Tarih</th>
                <th>#</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>#IT-12052010-FC00</td>
                <td>Ferhat ÇAKMAKOĞLU</td>
                <td>Bilgi İşlem</td>
                <td>12.05.2010</td>
                <td class="primary">Detaylar</td>
            </tr>
            <tr>
                <td>#SE-05062015-FC00</td>
                <td>Oğuz Alp ARSLAN</td>
                <td>Hizmet Birimi</td>
                <td>05.06.2015</td>
                <td class="primary">Detaylar</td>
            </tr>
            <tr>
                <td>#SU-07092020-FC00</td>
                <td>Hakan TANRIKULU</td>
                <td>Destek Birimi</td>
                <td>07.09.2020</td>
                <td class="primary">Detaylar</td>
            </tr>
            <tr>
                <td>#SU-07092020-FC00</td>
                <td>Hakan TANRIKULU</td>
                <td>Destek Birimi</td>
                <td>07.09.2020</td>
                <td class="primary">Detaylar</td>
            </tr>
            <tr>
                <td>#SU-07092020-FC00</td>
                <td>Hakan TANRIKULU</td>
                <td>Destek Birimi</td>
                <td>07.09.2020</td>
                <td class="primary">Detaylar</td>
            </tr>
        </tbody>
    </table>
    <a asp-action="EmployeeList" asp-controller="Employee">Tüm Personelleri Gör</a>
</div>

E-Belediye.UI/Views/Employee/EmployeeList.cshtml
@{
    ViewData["Title"] = "Personel Listesi";
    Layout = "_Layout";
}

<div class="recent-orders">
    <h2>Tüm Personeller</h2>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Ad Soyad</th>
                <th>Birimi</th>
                <th>İşe Başlama Tarih</th>
                <th>#</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>#IT-12052010-FC00</td>
                <td>Ferhat ÇAKMAKOĞLU</td>
                <td>Bilgi İşlem</td>
                <td>12.05.2010</td>
                <td class="primary">Detaylar</td>
            </tr>
            <tr>
                <td>#SE-05062015-FC00</td>
                <td>Oğuz Alp ARSLAN</td>
                <td>Hizmet Birimi</td>
                <td>05.06.2015</td>
                <td class="primary">Detaylar</td>
            </tr>
            <tr>
                <td>#SU-07092020-FC00</td>
                <td>Hakan TANRIKULU</td>
                <td>Destek Birimi</td>
                <td>07.09.2020</td>
                <td class="primary">Detaylar</td>
            </tr>
            <tr>
                <td>#SU-07092020-FC00</td>
                <td>Hakan TANRIKULU</td>
                <td>Destek Birimi</td>
                <td>07.09.2020</td>
                <td class="primary">Detaylar</td>
            </tr>
            <tr>
                <td>#SU-07092020-FC00</td>
                <td>Hakan TANRIKULU</td>
                <td>Destek Birimi</td>
                <td>07.09.2020</td>
                <td class="primary">Detaylar</td>
            </tr>
        </tbody>
    </table>
    <a href="#">1 - 2 - 3 - 4 </a>
</div>

E-Belediye.UI/Views/Employee/Index.cshtml
@{
    ViewData["Title"] = "Personel İşlemleri";
    Layout = "_Layout";
}

<head>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link rel="stylesheet" href="~/css/employee/employee.css" asp-append-version="true" />
</head>
<h1>Personel İşlemleri</h1>

<div class="analyse">
    <div class="sales">
        <div class="status">
            <div class="info">
                <h3>Toplam Personel Sayısı</h3>
                <h1>3685</h1>
            </div>
            <div class="progresss">
                <svg>
                    <circle cx="38" cy="38" r="36"></circle>
                </svg>
                <div class="percentage">
                    <p>+81%</p>
                </div>
            </div>
        </div>
    </div>
    <div class="visits">
        <div class="status">
            <div class="info">
                <h3>Beyaz Yaka Personel Sayısı</h3>
                <h1>850</h1>
            </div>
            <div class="progresss">
                <svg>
                    <circle cx="38" cy="38" r="36"></circle>
                </svg>
                <div class="percentage">
                    <p>94%</p>
                </div>
            </div>
        </div>
    </div>
    <div class="searches">
        <div class="status">
            <div class="info">
                <h3>Mavi Yaka Personel Sayısı</h3>
                <h1>2835</h1>
            </div>
            <div class="progresss">
                <svg>
                    <circle cx="38" cy="38" r="36"></circle>
                </svg>
                <div class="percentage">
                    <p>+21%</p>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="personel-chart">
    <canvas id="personelChart"></canvas>
    <script src="~/js/employee/employee.js"></script>
</div>

E-Belediye.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Dashboard";
    Layout = "_Layout";
}


<h1>Gösterge Paneli</h1>
<!-- Analyses -->
<div class="analyse">
    <div class="sales">
        <div class="status">
            <div class="info">
                <h3>Günlük Trafik</h3>
                <h1>65,024</h1>
            </div>
            <div class="progresss">
                <svg>
                    <circle cx="38" cy="38" r="36"></circle>
                </svg>
                <div class="percentage">
                    <p>+81%</p>
                </div>
            </div>
        </div>
    </div>
    <div class="visits">
        <div class="status">
            <div class="info">
                <h3>Aktif Oturum Sayısı</h3>
                <h1>389</h1>
            </div>
            <div class="progresss">
                <svg>
                    <circle cx="38" cy="38" r="36"></circle>
                </svg>
                <div class="percentage">
                    <p>94%</p>
                </div>
            </div>
        </div>
    </div>
    <div class="searches">
        <div class="status">
            <div class="info">
                <h3>Personel Sayısı</h3>
                <h1>3685</h1>
            </div>
            <div class="progresss">
                <svg>
                    <circle cx="38" cy="38" r="36"></circle>
                </svg>
                <div class="percentage">
                    <p>+21%</p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End of Analyses -->
<!-- New Users Section -->
<div class="new-users">
    <h2>Hızlı Kullanıcı Ekleme</h2>
    <div class="user-list">
        <div class="user">
            <img src="~/assets/sample-icons/profile-1.jpg">
            <h2>Ferhat ÇAKMAKOĞLU</h2>
            <p>54dk Önce Aktifti</p>
        </div>
        <div class="user">
            <img src="~/assets/sample-icons/profile-1.jpg">
            <h2>Oğuz Alp ARSLAN</h2>
            <p>10dk Önce Aktifti</p>
        </div>
        <div class="user">
            <img src="~/assets/sample-icons/profile-1.jpg">
            <h2>Hakan TANRIKULU</h2>
            <p>2 saat Önce Aktifti</p>
        </div>
        <div class="user">
            <img src="~/assets/sample-icons/plus.png">
            <h2>Ekleme yap</h2>
            <p>Kullanıcı Ekle</p>
        </div>
    </div>
</div>
<!-- End of New Users Section -->
<!-- Recent Orders Table -->
<div class="recent-orders">
    <h2>Son İşlemler</h2>
    <table>
        <thead>
            <tr>
                <th>İşlem ID</th>
                <th>İşlem Tipi</th>
                <th>İşlem Yapan</th>
                <th>Tarih</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>#018596321</td>
                <td>Su Faturası Ödeme</td>
                <td>Ferhat ÇAKMAKOĞLU</td>
                <td>27.01.2025 - 10:57</td>
                <td class="primary">Detaylar</td>
            </tr>
            <tr>
                <td>#589654123</td>
                <td>Elektrik Faturası Ödeme</td>
                <td>Oğuz Alp ARSLAN</td>
                <td>26.01.2025 - 15:57</td>
                <td class="primary">Detaylar</td>
            </tr>
            <tr>
                <td>#364178521</td>
                <td>Doğalgaz Faturası Ödeme</td>
                <td>Hakan TANRIKULU</td>
                <td>24.01.2025 - 13:57</td>
                <td class="primary">Detaylar</td>
            </tr>
        </tbody>
    </table>
    <a href="#">Tüm İşlemleri Görüntüle</a>
</div>
<!-- End of Recent Orders -->

E-Belediye.UI/Views/MessageBox/Index.cshtml
@{
    ViewData["Title"] = "Gelen Kutusu";
    Layout = "_Layout";
}
<head>
    <link rel="stylesheet" href="~/css/message-box/messageBox.css" />
</head>
<body>


    <h1>Mesaj Kutusu</h1>

    <div class="message-box">
        <div class="message-header" id="messageHeader">Sohbet: </div>
        <div class="messages" id="messages">
            <!-- Gelen mesajlar burada görünecek -->
        </div>
        <div class="input-area">
            <input type="text" id="messageInput" placeholder="Mesajınızı yazın...">
            <button id="sendButton">Gönder</button>
        </div>
    </div>

    <div class="inbox-list">
        <h3>Gelen Kutusu</h3>
        <table>
            <thead>
                <tr>
                    <th>Mesaj ID</th>
                    <th>Gönderen</th>
                    <th>Birimi</th>
                    <th>Gönderim Tarihi</th>
                </tr>
            </thead>
            <tbody>
                <tr class="unreaded" data-message="Merhaba! Nasılsın?">
                    <td>#859874</td>
                    <td>Ferhat ÇAKMAKOĞLU</td>
                    <td>Bilgi İşlem</td>
                    <td>19.10.2024</td>
                </tr>
                <tr class="unreaded" data-message="Toplantı saatini hatırlatır mısın?">
                    <td>#859875</td>
                    <td>Ayşe YILMAZ</td>
                    <td>İnsan Kaynakları</td>
                    <td>20.10.2024</td>
                </tr>
                <tr data-message="Proje raporunu gönderebilir misin?">
                    <td>#859876</td>
                    <td>Mehmet KARA</td>
                    <td>Finans</td>
                    <td>21.10.2024</td>
                </tr>
            </tbody>
        </table>
    </div>

    <script src="~/js/message-box/messageBox.js"></script>

</body>

E-Belediye.UI/Views/PastTransactions/Index.cshtml
@{
    ViewData["Title"] = "Geçmiş İşlemler";
    Layout = "_Layout";
}

<h1>Geçmiş İşlemler</h1>
<div class="analyse">
    <div class="sales">
        <div class="status">
            <div class="info">
                <h3>Günlük İşlem Sayısı</h3>
                <h1>102</h1>
            </div>
            <div class="progresss">
                <svg>
                    <circle cx="38" cy="38" r="36"></circle>
                </svg>
                <div class="percentage">
                    <p>+81%</p>
                </div>
            </div>
        </div>
    </div>
    <div class="visits">
        <div class="status">
            <div class="info">
                <h3>Haftalık İşlem Sayısı</h3>
                <h1>1465</h1>
            </div>
            <div class="progresss">
                <svg>
                    <circle cx="38" cy="38" r="36"></circle>
                </svg>
                <div class="percentage">
                    <p>94%</p>
                </div>
            </div>
        </div>
    </div>
    <div class="searches">
        <div class="status">
            <div class="info">
                <h3>Yıllık İşlem Sayısı</h3>
                <h1>40.145</h1>
            </div>
            <div class="progresss">
                <svg>
                    <circle cx="38" cy="38" r="36"></circle>
                </svg>
                <div class="percentage">
                    <p>+21%</p>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="recent-orders">
    <h2>Son Yapılan İşlemler</h2>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>İşlem Türü</th>
                <th>İşlem Yapan</th>
                <th>İşlem Tarihi</th>
                <th>#</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>#EE12052010-11452</td>
                <td>Vergi Ödeme</td>
                <td>Ferhat ÇAKMAKOĞLU</td>
                <td>12.05.2010</td>
                <td class="primary">Detaylar</td>
            </tr>
            <tr>
                <td>#EE12052010-11452</td>
                <td>Vergi Ödeme</td>
                <td>Ferhat ÇAKMAKOĞLU</td>
                <td>12.05.2010</td>
                <td class="primary">Detaylar</td>
            </tr>
            <tr>
                <td>#EE12052010-11452</td>
                <td>Vergi Ödeme</td>
                <td>Ferhat ÇAKMAKOĞLU</td>
                <td>12.05.2010</td>
                <td class="primary">Detaylar</td>
            </tr>
            <tr>
                <td>#EE12052010-11452</td>
                <td>Vergi Ödeme</td>
                <td>Ferhat ÇAKMAKOĞLU</td>
                <td>12.05.2010</td>
                <td class="primary">Detaylar</td>
            </tr>
            <tr>
                <td>#EE12052010-11452</td>
                <td>Vergi Ödeme</td>
                <td>Ferhat ÇAKMAKOĞLU</td>
                <td>12.05.2010</td>
                <td class="primary">Detaylar</td>
            </tr>
            <tr>
                <td>#EE12052010-11452</td>
                <td>Vergi Ödeme</td>
                <td>Ferhat ÇAKMAKOĞLU</td>
                <td>12.05.2010</td>
                <td class="primary">Detaylar</td>
            </tr>
        </tbody>
    </table>
    <a href="#">1 - 2 - 3 - 4</a>
</div>

E-Belediye.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>E-Belediye</title>
    <!--<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Sharp" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/right-side/rightSide.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/layout/layout.css" asp-append-version="true" />
</head>
<body>
    <div class="container">
        <aside>
            <div class="toggle">
                <div class="logo">
                    <img src="~/assets/sample-icons/logo.png">
                    <h2><span class="danger">E-</span>Belediye</h2>
                </div>
                <div class="close" id="close-btn">
                    <span class="material-icons-sharp">
                        close
                    </span>
                </div>
            </div>
            <div class="sidebar">
                <div class="menu-item">
                    <span class="material-icons-sharp">
                        dashboard
                    </span>
                    <a style="color:var(--color-info-dark)" asp-action="Index" asp-controller="Home">Dashboard</a>
                </div>
                <div class="menu-item">
                    <span class="material-icons-sharp">
                        person_outline
                    </span>
                    <h3>Personel İşlemleri</h3>
                    <div class="submenu">
                        <a asp-action="Index" asp-controller="Employee">Detaylar</a>
                        <a asp-action="AddEmployee" asp-controller="Employee">Personel İşlemleri</a>
                        <a asp-action="EmployeeList" asp-controller="Employee">Personel Listele</a>
                    </div>
                </div>
                <div class="menu-item">
                    <span class="material-icons-sharp">
                        receipt_long
                    </span>
                    <a style="color:var(--color-info-dark)" asp-action="Index" asp-controller="PastTransactions">Geçmiş İşlemler</a>
                </div>
                <div class="menu-item">
                    <span class="material-icons-sharp">
                        insights
                    </span>
                    <a style="color:var(--color-info-dark)" asp-action="Index" asp-controller="Analysis">Analizler</a>
                </div>
                <div class="menu-item">
                    <span class="material-icons-sharp">
                        mail_outline
                    </span>
                    <a style="color:var(--color-info-dark)" asp-action="Index" asp-controller="MessageBox">Gelen Kutusu</a>
                    <span class="message-count">27</span>
                </div>
                <div class="menu-item">
                    <span class="material-icons-sharp">
                        inventory
                    </span>
                    <a style="color:var(--color-info-dark)" asp-action="Index" asp-controller="TaskProcess">Görev İşlemleri </a>
                </div>
                <div>
                    <span class="material-icons-sharp">
                        logout
                    </span>
                    <h3>Çıkış Yap</h3>
                </div>
            </div>
        </aside>

        <main>
            @RenderBody()
        </main>

        <div class="right-section">
            <div class="nav">
                <button id="menu-btn">
                    <span class="material-icons-sharp">
                        menu
                    </span>
                </button>
                <div class="dark-mode" id="dark-theme">
                    <span class="material-icons-sharp active">
                        light_mode
                    </span>
                    <span class="material-icons-sharp">
                        dark_mode
                    </span>
                </div>

                <div class="profile">
                    <div class="info">
                        <p>Hoşgeldin, <b>Ferhat</b></p>
                        <small class="text-muted">Admin</small>
                    </div>
                    <div class="profile-photo">
                        <img src="~/assets/sample-icons/profile-1.jpg">
                    </div>
                </div>

            </div>
            <!-- End of Nav -->

            <div class="user-profile">
                <div class="logo">
                    <img src="~/assets/sample-icons/logo.png">
                    <h2><span class="danger">E-</span>Belediye</h2>
                    <p>Developed by INNOSA Tech &copy; </p>
                </div>
            </div>

            <div class="reminders">
                <div class="header">
                    <h2>Hatırlatıcılar</h2>
                    <span class="material-icons-sharp">
                        notifications_none
                    </span>
                </div>

                <div class="notification">
                    <div class="icon">
                        <span class="material-icons-sharp">
                            volume_up
                        </span>
                    </div>
                    <div class="content">
                        <div class="info">
                            <h3>Atölye Bakım Çalışması</h3>
                            <small class="text_muted">
                                08:00 AM - 12:00 PM
                            </small>
                        </div>
                        <span class="material-icons-sharp">
                            more_vert
                        </span>
                    </div>
                </div>

                <div class="notification deactive">
                    <div class="icon">
                        <span class="material-icons-sharp">
                            edit
                        </span>
                    </div>
                    <div class="content">
                        <div class="info">
                            <h3>Rapor Hazırlama</h3>
                            <small class="text_muted">
                                12:30 PM - 13:30 PM
                            </small>
                        </div>
                        <span class="material-icons-sharp">
                            more_vert
                        </span>
                    </div>
                </div>

                <div class="notification add-reminder">
                    <div>
                        <span class="material-icons-sharp">
                            add
                        </span>
                        <h3>Hatırlatıcı Ekle</h3>
                    </div>
                </div>

            </div>

        </div>
    </div>
    <script src="~/js/layout/layout.js" asp-append-version="true"></script>
    <script src="~/js/right-side/rightSide.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <!--
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    -->

    @* @await RenderSectionAsync("Scripts", required: false) *@
</body>
</html>

E-Belediye.UI/Views/TaskProcess/Index.cshtml
@{
    ViewData["Title"] = "Görev İşlemleri";
    Layout = "_Layout";
}

<head>
    <link rel="stylesheet" href="~/css/task-process/taskProcess.css" />
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>
    <h1>Görev Yönetimi</h1>

    <div class="task-process-div">
        <form id="taskForm">
            <label for="personel">Personel:</label>
            <select id="personel" name="personel" required>
                <option value="Ahmet">Ahmet</option>
                <option value="Mehmet">Mehmet</option>
                <option value="Ayşe">Ayşe</option>
                <option value="Fatma">Fatma</option>
            </select>

            <label for="gorev">Görev:</label>
            <input type="text" id="gorev" name="gorev" required>

            <button type="submit">Görev Ata</button>
        </form>

    </div>
    <!-- Görev Listesi -->
    <div class="recent-orders task-table">
        <h2>Görev Listesi</h2>
        <table>
            <thead>
                <tr>
                    <th>Görev ID</th>
                    <th>Ad Soyad</th>
                    <th>Birimi</th>
                    <th>Görev Başlama Tarihi</th>
                    <th>Görev Bitiş Tarihi</th>
                    <th>#</th>
                </tr>
            </thead>
            <tbody>
                <tr class="uncompleted">
                    <td>#IT-12052010-FC00</td>
                    <td>Ferhat ÇAKMAKOĞLU</td>
                    <td>Bilgi İşlem</td>
                    <td>12.05.2010</td>
                    <td>12.05.2010</td>
                    <td class="primary">Detaylar</td>
                </tr>
                <tr class="completed">
                    <td>#SE-05062015-FC00</td>
                    <td>Oğuz Alp ARSLAN</td>
                    <td>Hizmet Birimi</td>
                    <td>05.06.2015</td>
                    <td>12.05.2010</td>
                    <td class="primary">Detaylar</td>
                </tr>
                <tr>
                    <td>#SU-07092020-FC00</td>
                    <td>Hakan TANRIKULU</td>
                    <td>Destek Birimi</td>
                    <td>07.09.2020</td>
                    <td>12.05.2010</td>
                    <td class="primary">Detaylar</td>
                </tr>
                <tr>
                    <td>#SU-07092020-FC00</td>
                    <td>Hakan TANRIKULU</td>
                    <td>Destek Birimi</td>
                    <td>07.09.2020</td>
                    <td>12.05.2010</td>
                    <td class="primary">Detaylar</td>
                </tr>
                <tr>
            </tbody>
        </table>
        <a href="#">1 - 2 - 3 - 4</a>
    </div>

    <script src="~/js/task-process/taskProcess.js"></script>
</body>